version: "3.2"
services:
  app:
    container_name: auth
    command: node src/server.js
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - published: ${APP_PORT:-3000}
        target: 3000
    volumes:
      - .:/app/
    environment:
      JWT_SECRET: ${JWT_SECRET}
  interview:
    container_name: interview
    command: >
      sh -c "npm run test
             node interview/server.js"
    build:
      context: .
      dockerfile: Dockerfile_interview
    ports:
      - published: ${APP_PORT:-3001}
        target: 3001
    volumes:
      - .:/app/
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_NAME: ${DATABASE_NAME}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      database:
        condition: service_healthy
  database:
    restart: always
    container_name: database
    volumes:
      - "./database_script.sql:/docker-entrypoint-initdb.d/1.sql"
    build:
      context: .
      dockerfile: Dockerfile_database
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - published: ${APP_PORT:-3307}
        target: 3307
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 2
