name: actions

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      JWT_SECRET: ${{steps.dotenv.outputs.JWT_SECRET}}
      DATABASE_HOST: ${{steps.dotenv.outputs.DATABASE_HOST}}
      DATABASE_USER: ${{steps.dotenv.outputs.DATABASE_USER}}
      DATABASE_NAME: ${{steps.dotenv.outputs.DATABASE_NAME}}

    steps:
    - uses: ./.github/actions/dotenv-action
    - name: Build the docker-compose stack
      run: docker-compose -f docker-compose.yml  up -d
    - name: Check running containers
      run: docker ps -a
    - name: Check logs
      run: docker logs backend
